name: core-build
on:
  push:
    branches:
        - 'master'
  pull_request:

jobs:
  build:
    uses: AnchyDev/reusable-workflows/.github/workflows/core_build_modules.yml
    with:
      module_repo: ${{ github.event.repository.name }}
