name: core-build
on:
  workflow_dispatch:
    branches:
        - 'master'

jobs:
  build:
    uses: anchydev/reusable-workflows/.github/workflows/core_build_modules.yml@main
    with:
      module_repo: ${{ github.event.repository.name }}
